name: Go

on:
  release:
    types: [created]

jobs:

  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERUSER }}
        password: ${{ secrets.DOCKERPASSWORD }}

    - name: debug
      run: echo REF=${GITHUB_REF##*/}

    - name: release
      uses: wangyoucao577/go-release-action@v1.22
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
        project_path: ./rocktest/rocktest/main
        pre_command: apt update && apt install -y unixodbc unixodbc-dev


    - name: Build Docker image
      run: ./rocktest/integ/build.sh ${GITHUB_REF##*/}